export const title = "枫枫知道后台管理系统1"
export const slogan = "枫枫知道"
export const enSlogan = "fengfengzhidao"
export const ico = "/logo.png"
// export const ico = "https://fanyi-cdn.cdn.bcebos.com/webStatic/translation/img/favicon/favicon-32x32.png"